title: Engineering By Trade
email: engineeringbytrade@gmail.com
description: >-
  A resource for anyone interested in software development
baseurl: ""
url: "http://engineeringbytrade.com"
twitter_username: engbytrade
github_username:  engineeringbytrade
facebook_username: engineeringbytrade

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Google
google_analytics: UA-177028079-1
google_adsense: ca-pub-5312431970919692

#icon
masthead: /assets/default-icon.jpg